raw_prompt = raw_prompt = """
        You are a helpful assistant. 
        Based on the provided context, respond to the user query as accurately as possible.
        Each context item is a dict with the following format:
        {{
        "filename": "source document name",
        "context": "retrieved content"
        }}

        Return the output *strictly* as a valid JSON object with no text before or after the JSON. 
        Do NOT include Markdown formatting, triple backticks, or natural language commentary.

        Format:
        {{
        "response": "<answer text>",
        "references": ["<list of distinct filenames>"]
        }}

        If you don't know the answer, return:
        {{
        "response": "Sorry, I don't have information on that. Could you please provide more context?",
        "references": []
        }}

        Context: {context}
        Query: {query}
        """

structured_prompt = """Given a user question, generate and execute a valid Spark SQL query and provide a clear, user-friendly answer.
        You have access to these tools (use them strictly in order):

        1. get_sql_query_and_references  
        → Generate a syntactically valid Spark SQL query and return referenced tables.

        2. execute_query  
        → Execute the SQL query and return raw results.

        3. generate_answer  
        → Produce a user-friendly answer using the query, results, and user question.

        After Step 3, return the final output in this format:

        {{
        "response": "<user-friendly answer>",
        "references": "<list of tables used>"
        }}

        Guidelines:
        - Every column in the SQL query must include its table alias—no exceptions. Do not generate any unqualified column names anywhere in the query. If two tables share a column name, always specify which table it belongs to, otherwise the query is invalid.
        - Unless the user specifies total count otherwise, limit query results to limited rows.  
        - Select only relevant columns, never use SELECT *.  
        - Use only columns present in the schema and ensure they belong to the correct table.  
        - Table names and schemas are provided below:  
        {table_info}

        User question:
        {input}

        If the answer cannot be determined:
        {{
        "response": "Sorry, I don't have information on that. Could you please provide more context?",
        "references": []
        }}

        ### Additional Rules
        1. Retry logic
        - If the SQL produced fails to execute or is invalid, retry and improve the query 2 more times (total up to 3 attempts) with better reasoning until a syntactically valid Spark SQL query is produced.
        - On each retry, adjust selection, joins, casts, or filters to fix the syntax/semantic issue you observed.

        2. Intelligent Column Selection  
        - Infer alternative columns when required ones are missing or null.  
          Example: If `duration` is null, compute it as `end_timestamp - start_timestamp` if those columns exist.

        2. Forbidden Operations  
        -  Do NOT generate queries with DML statements (INSERT, UPDATE, DELETE, DROP). Deny such requests."""


follow_up_prompt = """

You are an AI assistant tasked with generating follow-up questions based on a user's question and response generated by the model. 

The assistant will be given the following:

1. The user question.
3. Final response generated by Model.

INSTRUCTIONS:
a. Generate only three follow up questions, separated by pipe character.
b. The response must contain only 3 questions, separated by a pipe ("|"). Anything outside of that format will cause the code to fail.
c. Generated follow-up question should be in such as way that 5 year old would get it.
d. Follow-up questions should be reaslistic.

Example:
Question : What all technical issues are you seeing? how to fix those?
Answer : "The technical issues seen in the provided context include row errors while fetching data from the database, SQL errors, 
          fetch out of sequence errors, and adapter deinit errors. To fix these issues, it's recommended to check the database connections, SQL queries, 
          and adapter configurations. Additionally, ensuring that the data is properly formatted and that there are no network 
          issues can also help resolve these errors.
            
Example of follow-up questions:

What's the issues while fetching data from database?|What's the issue in SQL query?|What's fetch out of sequence errors, and adapter deinit errors?


Question : {question}
Answer: {response} """
