import time,os
import numpy as np
from typing import List
from Utilities.llmUtils import get_databricks_chatmodel
from Utilities.prompts import follow_up_prompt
from databricks.vector_search.client import VectorSearchClient 
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from databricks_langchain import DatabricksEmbeddings


def check_index_status():
    try:
        index_name = os.getenv("DATABRICKS_IDMCLOGS_INDEX")
        client = VectorSearchClient(disable_notice=True)
        index = client.get_index(index_name=index_name)
        while not index.describe().get('status')['ready']:
            print("Waiting for index to be ONLINE...")
            time.sleep(5)
    except Exception as error:
        print(error)
        raise error
    
    return index 

def get_confindence_score(question:str,response:str) -> int:
    """
    This function computes similarity between question and response generated by model
    """
   
    endpoint = os.getenv("DATABRICKS_EMBEDDING_ENDPOINT")
    embeddings = DatabricksEmbeddings(
        endpoint=endpoint
    )
    question_embedding = embeddings.embed_query(question)
    response_embedding = embeddings.embed_query(response)
    vec1 = np.array(question_embedding) / np.linalg.norm(question_embedding)
    vec2 = np.array(response_embedding) / np.linalg.norm(response_embedding)
    score = np.dot(vec1, vec2)
    return round((score + 1) / 2,2)


def get_follow_up_questions(question:str,response:str) -> List[str]:
    model = get_databricks_chatmodel() 
    prompt = ChatPromptTemplate.from_template(follow_up_prompt)
    chain = prompt | model | StrOutputParser()
    answer = chain.invoke({"question":question,"response":response})
    return [question.strip() for question in answer.split("|")]